server:
  port: 8080

currencylayer:
  accessKey: bb3d1cce303912a0260abfed09b3538a
  baseUrl: http://api.currencylayer.com/

spring:

  application:
    name: exchange-service

  profiles:
    active: micro

  datasource:
    url: jdbc:postgresql://localhost:5432/currency_db
    username: sadstill
    password: 2304
    driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.yaml

