server:
  port: 8765
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:ssl/sadstill_ssl_rootca_.pfx
    key-store-password: Alex81

spring:
  application:
    name: api-gateway

  config:
    import: configserver:http://localhost:8888



