spring:
  application:
    name: exchange-rate-management

  config:
    import: configserver:http://localhost:8888

  profiles:
    active: micro

  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.yaml

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: cr1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://localhost:5432/currency_db
    username: sadstill
    password: 2304
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:ssl/sadstill_ssl_rootca_.pfx
    key-store-password: Alex81
