server:
  port: 8989

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

currencylayer:
  accessKey: bb3d1cce303912a0260abfed09b3538a
  baseUrl: http://api.currencylayer.com/