server:
  port: 8888

spring:
  application:
    name: github-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sadstill/prop-test
          clone-on-start: true
          basedir: file://Users/sadstill/git-repo
          username: sadstill
          password: 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
          default-label: main

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
